package no.hild1.bank.telepay;

import java.util.regex.Matcher;
import java.util.regex.Pattern;

import no.hild1.bank.TelepayParserException;
import org.apache.commons.logging.Log;
import org.apache.commons.logging.LogFactory;

public class Betfor22 extends Betfor {
    public Betfor22(BetforHeader header, String stringRecord)  throws TelepayParserException {
        super(header, stringRecord);
        log.info(this.stringRecord);
        m = this.betforPattern.matcher(this.stringRecord);

        log.info(this.betforRegexp);
        if (m.matches()) {
            log.info("Found Betfor21");
        } else {
            throw new TelepayParserException(header.getRecordNum(), "Did not QWERGQWETHWETmatch BETFOR21");
        }
    }

    public String get(Element e) {
        return m.group(((Element)e).name());
    }

    /* makeBetforData.sh START */
	/* Generated by makeBetforData.sh */
	private static Log log = LogFactory.getLog(Betfor22.class);
	private static String betforRegexp = "^(?<"+ Element.APPLICATIONHEADER.name() + ">.{40})"
		+ "(?<"+ Element.TRANSACTIONCODE.name() + ">.{8})"
		+ "(?<"+ Element.ENTERPRISENUMBER.name() + ">.{11})"
		+ "(?<"+ Element.ACCOUNTNUMBER.name() + ">.{11})"
		+ "(?<"+ Element.SEQUENCECONTROL.name() + ">.{4})"
		+ "(?<"+ Element.REFERENCENUMBER.name() + ">.{6})"
		+ "(?<"+ Element.PAYEESACCOUNTNUMBER.name() + ">.{11})"
		+ "(?<"+ Element.PAYEESNAME.name() + ">.{30})"
		+ "(?<"+ Element.AMOUNT.name() + ">.{15})"
		+ "(?<"+ Element.CANCELLATIONCODE.name() + ">.{1})"
		+ "(?<"+ Element.OWNREFERENCE1.name() + ">.{35})"
		+ "(?<"+ Element.RESERVED1.name() + ">.{110})"
		+ "(?<"+ Element.OWNREFERENCE2.name() + ">.{10})"
		+ "(?<"+ Element.SERIALNUMBER.name() + ">.{4})"
		+ "(?<"+ Element.CANCELLATIONCAUSE.name() + ">.{1})"
		+ "(?<"+ Element.RESERVED2.name() + ">.{23})"
		+ "$";
	public static Pattern betforPattern = Pattern.compile(betforRegexp);
	Matcher m;
	public enum Element {
		APPLICATIONHEADER, TRANSACTIONCODE, ENTERPRISENUMBER, 
		ACCOUNTNUMBER, SEQUENCECONTROL, REFERENCENUMBER, 
		PAYEESACCOUNTNUMBER, PAYEESNAME, AMOUNT, 
		CANCELLATIONCODE, OWNREFERENCE1, RESERVED1, 
		OWNREFERENCE2, SERIALNUMBER, CANCELLATIONCAUSE, 
		RESERVED2
	}
    /* makeBetforData.sh STOP */
}
