package no.hild1.bank.telepay;

import java.util.regex.Matcher;
import java.util.regex.Pattern;
import org.apache.commons.logging.Log;
import org.apache.commons.logging.LogFactory;

public class Betfor23 extends Betfor {

    public Betfor23(BetforHeader header, String stringRecord) {
        super(header, stringRecord);
    }

    public String get(Element e) {
        return m.group(((Element)e).name());
    }

    /* makeBetforData.sh START */
	/* Generated by makeBetforData.sh */
    private static Log log = LogFactory.getLog(Betfor23.class);
    private static String betforRegexp = "^(APPLICATIONHEADER.{40})"
            + "(?<"+ Element.TRANSACTIONCODE.name() + ">.{8}  "
            + "(?<"+ Element.ENTERPRISENUMBER.name() + ">.{11}  "
            + "(?<"+ Element.ACCOUNTNUMBER.name() + ">.{11}  "
            + "(?<"+ Element.SEQUENCECONTROL.name() + ">.{4}  "
            + "(?<"+ Element.REFERENCENUMBER.name() + ">.{6}  "
            + "(?<"+ Element.PAYEEREFINVOICE.name() + ">.{120}  "
            + "(?<"+ Element.KID.name() + ">.{27}  "
            + "(?<"+ Element.OWNREFERENCEINVOICE.name() + ">.{30}  "
            + "(?<"+ Element.INVOICEAMOUNT.name() + ">.{15}  "
            + "(?<"+ Element.DEBITCREDITCODECANCELLATIONCODE.name() + ">.{1}  "
            + "(?<"+ Element.INVOICENUMBER.name() + ">.{20}  "
            + "(?<"+ Element.SERIALNUMBER.name() + ">.{3}  "
            + "(?<"+ Element.CANCELLATIONCAUSE.name() + ">.{1}  "
            + "(?<"+ Element.CUSTOMERNUMBER.name() + ">.{15}  "
            + "(?<"+ Element.INVOICEDATE.name() + ">.{8}  "
            + "$";
    public static Pattern betforPattern = Pattern.compile(betforRegexp);
    Matcher m;
    public enum Element {
        APPLICATIONHEADER, TRANSACTIONCODE, ENTERPRISENUMBER,
        ACCOUNTNUMBER, SEQUENCECONTROL, REFERENCENUMBER,
        PAYEEREFINVOICE, KID, OWNREFERENCEINVOICE,
        INVOICEAMOUNT, DEBITCREDITCODECANCELLATIONCODE, INVOICENUMBER,
        SERIALNUMBER, CANCELLATIONCAUSE, CUSTOMERNUMBER,
        INVOICEDATE
    }
    /* makeBetforData.sh STOP */
}
