package no.hild1.bank.telepay;

import no.hild1.bank.TelepayParserException;
import org.apache.commons.logging.Log;
import org.apache.commons.logging.LogFactory;
import org.jdesktop.swingx.JXCollapsiblePane;

import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.regex.Matcher;
import java.util.regex.Pattern;

public class Betfor01 extends Betfor {

    public Betfor01(BetforHeader header, String stringRecord)  throws TelepayParserException {
        super(header, stringRecord);
        log.info(this.stringRecord);
        m = this.betforPattern.matcher(this.stringRecord);

        log.info(this.betforRegexp);
        if (m.matches()) {
            log.info("Record #" + header.getRecordNum()
                    + " (staring at line " + (header.getRecordNum()*4) + ") is a BETFOR01");
        } else {
            String error = "Failed to parse record #" + header.getRecordNum()
                    + " (staring at line " + (header.getRecordNum()*4) + ") as a BETFOR01";
            log.error(error);
            throw new TelepayParserException(header.getRecordNum(),
                    error);
        }
    }

    JButton showHideButton;
    JXCollapsiblePane mainCPanel;
    public JPanel getPanel() {
        JPanel panel = new JPanel();
        JTable table = new JTable();
        table.setEnabled(false);
        DefaultTableModel model = new DefaultTableModel();
        model.addColumn("Key");
        model.addColumn("Value");
        String[] keyValue = new String[2];
        for(Element e: Element.values()) {
            keyValue[0] = e.name();
            keyValue[1] = get(e);
            model.addRow(keyValue);
        }
        table.setModel(model);
        table.getColumn(0).setPreferredWidth(35);
        table.getColumn(1).setPreferredWidth(120);
        panel.setLayout(new BoxLayout(panel, BoxLayout.PAGE_AXIS));
        showHideButton = new JButton("Record #" + header.getRecordNum() + ", BETFOR" + header.getBetforTypeString());
        showHideButton.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent actionEvent) {
                mainCPanel.setCollapsed(!mainCPanel.isCollapsed());
            }
        });
        panel.add(showHideButton);
        mainCPanel = new JXCollapsiblePane();
        mainCPanel.setCollapsed(true);
        mainCPanel.add(table);
        mainCPanel.setCollapsed(false);
        panel.add(mainCPanel);
        return panel;
    }

    public String get(Element e) {
        return m.group(((Element)e).name());
    @Override
    public Color getColor(ElementInterface e) {
        return null;
    }

    /* makeBetforData.sh START */
	/* Generated by makeBetforData.sh */
	private static Log log = LogFactory.getLog(Betfor01.class);
	private static String betforRegexp = "^(?<"+ Element.APPLICATIONHEADER.name() + ">.{40})"
		+ "(?<"+ Element.TRANSACTIONCODE.name() + ">.{8})"
		+ "(?<"+ Element.ENTERPRISENUMBER.name() + ">.{11})"
		+ "(?<"+ Element.ACCOUNTNUMBER.name() + ">.{11})"
		+ "(?<"+ Element.SEQUENCECONTROL.name() + ">.{4})"
		+ "(?<"+ Element.REFERENCENUMBER.name() + ">.{6})"
		+ "(?<"+ Element.PAYMENTDATE.name() + ">.{6})"
		+ "(?<"+ Element.OWNREFERENCEORDER.name() + ">.{30})"
		+ "(?<"+ Element.PAYMENTCURRENCY.name() + ">.{3})"
		+ "(?<"+ Element.INVOICECURRENCY.name() + ">.{3})"
		+ "(?<"+ Element.CHARGESABROAD.name() + ">.{3})"
		+ "(?<"+ Element.CHARGESINNORWAY.name() + ">.{3})"
		+ "(?<"+ Element.NOTIFICATIONINDICATOR.name() + ">.{30})"
		+ "(?<"+ Element.PRIORITYCODE.name() + ">.{1})"
		+ "(?<"+ Element.AGREEDEXCHANGERATE.name() + ">.{8})"
		+ "(?<"+ Element.FORWARDCONTRACTNO.name() + ">.{6})"
		+ "(?<"+ Element.FORWARDCONTRACTEXCHRATE.name() + ">.{8})"
		+ "(?<"+ Element.CHEQUECODE.name() + ">.{1})"
		+ "(?<"+ Element.VALUEDATERECEIVINGBANK.name() + ">.{6})"
		+ "(?<"+ Element.RESERVED1.name() + ">.{2})"
		+ "(?<"+ Element.ACTUALEXCHANGERATE.name() + ">.{12})"
		+ "(?<"+ Element.EXECUTIONREF2.name() + ">.{12})"
		+ "(?<"+ Element.AMOUNTDEBITED.name() + ">.{16})"
		+ "(?<"+ Element.AMOUNTTRANSFERRED.name() + ">.{16})"
		+ "(?<"+ Element.CLIENTREFERENCE.name() + ">.{5})"
		+ "(?<"+ Element.EXECUTIONREF1.name() + ">.{6})"
		+ "(?<"+ Element.DEALMADEWITH.name() + ">.{6})"
		+ "(?<"+ Element.CANCELLATIONCODE.name() + ">.{1})"
		+ "(?<"+ Element.CLEARINGCODE.name() + ">.{1})"
		+ "(?<"+ Element.VALUEDATE.name() + ">.{6})"
		+ "(?<"+ Element.FEE.name() + ">.{9})"
		+ "(?<"+ Element.RATEAGAINSTNOK.name() + ">.{12})"
		+ "(?<"+ Element.CANCELLATIONCAUSE.name() + ">.{1})"
		+ "(?<"+ Element.ORDEREDTRANSFERREDAMOUNT.name() + ">.{16})"
		+ "(?<"+ Element.PRICEINFO.name() + ">.{1})"
		+ "(?<"+ Element.RESERVED2.name() + ">.{10})"
		+ "$";
	public static Pattern betforPattern = Pattern.compile(betforRegexp);
	public enum Element implements ElementInterface {
		APPLICATIONHEADER, TRANSACTIONCODE, ENTERPRISENUMBER, 
		ACCOUNTNUMBER, SEQUENCECONTROL, REFERENCENUMBER, 
		PAYMENTDATE, OWNREFERENCEORDER, PAYMENTCURRENCY, 
		INVOICECURRENCY, CHARGESABROAD, CHARGESINNORWAY, 
		NOTIFICATIONINDICATOR, PRIORITYCODE, AGREEDEXCHANGERATE, 
		FORWARDCONTRACTNO, FORWARDCONTRACTEXCHRATE, CHEQUECODE, 
		VALUEDATERECEIVINGBANK, RESERVED1, ACTUALEXCHANGERATE, 
		EXECUTIONREF2, AMOUNTDEBITED, AMOUNTTRANSFERRED, 
		CLIENTREFERENCE, EXECUTIONREF1, DEALMADEWITH, 
		CANCELLATIONCODE, CLEARINGCODE, VALUEDATE, 
		FEE, RATEAGAINSTNOK, CANCELLATIONCAUSE, 
		ORDEREDTRANSFERREDAMOUNT, PRICEINFO, RESERVED2
	}
	public ElementInterface[] getElements() { return Element.values(); }
    /* makeBetforData.sh STOP */
}
