BEGIN { ENUM="\tpublic enum Element {\n\t\t"; REGEXP=""; TOTAL=0; RECORD=1; COUNT=0; }
{ 
    if (RECORD == 1) {
        RECORD = 2;
        CHECKTOTAL=$1;
    } else if (RECORD == 2) {
        RECORD = 3;
        ENUM = ENUM $1;
        REGEXP = "\"^(?<\"+ Element." $1 ".name() + \">.{" $2 "})\"";
    } else {
        COUNT = COUNT + 1;
        ENUM = ENUM ", ";
        if (COUNT == 3) {
            ENUM = ENUM "\n\t\t";
            COUNT=0;
        }
        REGEXP = REGEXP "\n\t\t+ \"(?<\"+ Element." $1 ".name() + \">.{" $2 "})\"";
        ENUM = ENUM $1;
    }
    REGEXP = REGEXP "";
    TOTAL=TOTAL+$2;
}
END { 
    if (TOTAL == CHECKTOTAL) {
        split(FILENAME,name,".");
        print "\t/* Generated by makeBetforData.sh */";
        print "\tprivate static Log log = LogFactory.getLog(" name[1] ".class);"
        if (FILENAME != "BetforHeader.layout") {
            print "\tprivate static String betforRegexp = " REGEXP "\t\t+ \"$\";";
        } else {
            print "\tprivate static String betforRegexp = " REGEXP ";";
        }
        print "\tpublic static Pattern betforPattern = Pattern.compile(betforRegexp);"
        print "\tMatcher m;\n" ENUM "\n\t}"; 
    } else {
            print "\t// Total length of elements in " FILENAME " is " TOTAL " not " CHECKTOTAL " as it should "
    }
}
